### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by evd316**
I corresponded the translation between the ENG/UKR version for our application and the UKR version for the Chrome web browser extension for PC.

### CODE REVIEW

**Comment by evd316** [comment]
I discovered that the ENG versions are different:

github.com/kitadai31/revanced-patches-android6-7/blob/revanced-extended/src/main/resources/youtube/settings/host/values/strings.xml

github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/resources/youtube/settings/host/values/strings.xml

And why? Do you have your own ENG version and, accordingly, a UKR/RUS version? Maybe I don't understand something, sorry.

**Comment by kitadai31** [comment]
because this version is based on very old RVX

**Comment by evd316** [comment]
Oh, I see.
Nevertheless, I am completely guided by your ENG version, PR#58 too. And in other places I look for synonyms that are more appropriate in meaning. So everything matches YOUR ENG version.

**Comment by kitadai31** [comment]
Hey, sorry for waiting long
I'm going to release a patch update a week later
your Ukrainian translations fixes will be shipped

I merge this pull request just before release update
So, If you have any other translations you would like to correct, please push them to this PR

**Comment by evd316** [comment]
Hi! I'll see, today-tomorrow add to the PR#58
if I can figure out how to add changes to the current PR.

**Comment by kitadai31** [comment]
just edit the files (src/main/resources/youtube/translations/uk-rUA/strings.xml) on the `patch-1` branch to add change to PR.

**Comment by evd316** [comment]
That's all for today.

I would like to get some advice for the future — whether it is necessary to display SponsorBlock-notifications equal (word-by-word) as in the menu:
Безымянный
"Пауза/Заставка" and 'notification' says "Пропущено вступ". ENG to UKR is not translated verbatim, but everything is fine for understanding. Moreover, there is an explanation below.

**Comment by kitadai31** [comment]
I don't think it is needed.

**Pull request merged**
