### PR TITLE
Update UKR strings.xml

### PR DESCRIPTION
**Pull request by evd316**
a little new stuff

### CODE REVIEW

**Comment by kitadai31** [comment]
I changed and added these strings
Please translate

Modified:

```xml
    <string name="revanced_spoof_app_version_summary">"Tricks the YouTube client version to enable the new layout or restore old layout.
Empty = No spoofing
Please read \"More information about Spoof app version\""</string>
    <string name="revanced_newer_android_warning_body">"This YouTube ReVanced is for Android 6.0-7.1, but this device is Android %1$s.
You may have installed the wrong version of ReVanced.

Tap \"OK\" to exit the app.

<i>Note: If you just want to use the old UI design, you can use the latest RVX and set the "Spoof app version" setting to 17.33.42.</i>"</string>
```

Added:

```xml
    <!-- PreferenceScreen: Miscellaneous, PreferenceCategory: Miscellaneous, PreferenceScreen: Spoof client -->
    <string name="revanced_preference_screen_spoof_client_title">Spoof client</string>
    <string name="revanced_preference_screen_spoof_client_summary">Spoof the client to prevent playback issues.</string>
    <string name="revanced_spoof_client_title">Spoof client</string>
    <string name="revanced_spoof_client_summary_on">Client is spoofed.</string>
    <string name="revanced_spoof_client_summary_off">"Client is not spoofed. Video playback may not work."</string>
    <string name="revanced_spoof_client_stats_for_nerds_title">Show in Stats for nerds</string>
    <string name="revanced_spoof_client_stats_for_nerds_summary_on">Spoofed client is shown in Stats for nerds.</string>
    <string name="revanced_spoof_client_stats_for_nerds_summary_off">Spoofed client is hidden in Stats for nerds.</string>

    <!-- PreferenceScreen: Miscellaneous, PreferenceCategory: Miscellaneous, PreferenceScreen: Spoof client, PreferenceCategory: Spoof client options -->
    <string name="revanced_preference_category_spoof_client_options">Spoof client options</string>
    <string name="revanced_spoof_client_general_title">General</string>
    <string name="revanced_spoof_client_livestream_title">Live streams</string>
    <string name="revanced_spoof_client_shorts_title">Shorts, Clips</string>
    <string name="revanced_spoof_client_fallback_title">Unplayable video</string>
    <string name="revanced_spoof_client_options_entry_ios">iOS</string>
    <string name="revanced_spoof_client_options_entry_android">Android</string>
    <string name="revanced_spoof_client_options_entry_android_embedded_player">Android Embedded Player</string>
    <string name="revanced_spoof_client_options_entry_android_testsuite">Android Testsuite</string>
    <string name="revanced_spoof_client_options_entry_android_unplugged">Android TV</string>
    <string name="revanced_spoof_client_options_entry_android_vr">Android VR</string>
    <string name="revanced_spoof_client_options_entry_tvhtml5_simply_embedded_player">TV HTML5</string>
    <string name="revanced_spoof_client_options_entry_web">Web</string>

    <!-- PreferenceScreen: Miscellaneous, PreferenceCategory: Miscellaneous, PreferenceScreen: Spoof client, PreferenceCategory: About -->
    <string name="revanced_preference_category_spoof_client_about">About</string>

    <string name="revanced_spoof_client_use_ios_title">iOS</string>
    <string name="revanced_spoof_client_use_ios_summary">"Spoof client to iOS.

Side effects include:
• No HDR video.
• Higher video qualities may be missing.
• Watch history does not work with a brand account.
• Live streams cannot play as audio only.
• Live streams not available on Android 8.0 or below."</string>
    <string name="revanced_spoof_client_use_android_testsuite_title">Android Testsuite</string>
    <string name="revanced_spoof_client_use_android_testsuite_summary">"Spoof client to Android Testsuite.

Side effects include:
• No HDR video.
• Audio track menu is missing.
• Subtitles are not available.
• Seekbar thumbnails are not shown"</string>
    <string name="revanced_spoof_client_use_android_tv_title">Android TV</string>
    <string name="revanced_spoof_client_use_android_tv_summary">"Spoof client to Android TV (YouTube TV).

Side effects include:
• No HDR video.
• Audio track menu is missing.
• Subtitles are not available.
• Some live streams are not supported for playback."</string>
    <string name="revanced_spoof_client_use_android_vr_title">Android VR</string>
    <string name="revanced_spoof_client_use_android_vr_summary">"Spoof client to Android VR.

Side effects include:
• No HDR video.
• Paused videos can randomly resume.
• Kids videos do not playback."</string>
```

The added strings are similer to official RVX's strings
You can copy the translations from RVX's translations
But it's a bit different

**Comment by evd316** [comment]
And where can I watch official RVX project?
How urgently is translation needed?

**Comment by kitadai31** [comment]
This is translation of official RVX

https://github.com/inotia00/revanced-patches/blob/a71ce6b88cceb135492e10f6e7a20f7157e9133d/src/main/resources/youtube/translations/uk-rUA/strings.xml#L1329-L1378

I would appreciate it if you could submit it within 8 hours.

**Comment by evd316** [comment]
"Added: …" just add to the end of the file after string 623??

**Comment by kitadai31** [comment]
Yes.
Insert before the last </resources> line

**Comment by evd316** [comment]
Done!

**Comment by kitadai31** [comment]
Thank you!

**Comment by evd316** [comment]
But I don’t understand what “… brand account” is? So as not to think too long here I took the translation from official RVX.

**Comment by evd316** [comment]
String 610 corrected, \\" missing.

**Pull request merged**
