### PR TITLE
Update uk-rUA strings.xml

### PR DESCRIPTION
**Pull request by evd316**
Corrected cases, style, appropriateness, conciseness. Added strings 585-590 from ENG to UKR, because these items are not translated at all into the program menu.

### CODE REVIEW

**Review by kitadai31 — CHANGES_REQUESTED** [review]
Some hyphen symbols are replaced with special characters (Unicode one?), but I don't think this change is needed.
Please revert hyphen change

**Comment by evd316** [comment]
This is linguistically correct and for beauty too.
"-" this is 'hyphen-minus', on the keyboard numeric pad or [Alt+0045], code U+002D
"–" this is 'N-dash', on the keyboard [Alt+0150], code U+2013
They are both, as I understand it, Unicode. But I'll return it back (7 pcs).

**Review by kitadai31 — APPROVED** [review]

**Comment by kitadai31** [comment]
Ah, I didn't know about it
I'm not familiar with European symbols, sorry

Thank you for contributing!

**Comment by evd316** [comment]
If I need to change something else, should I continue here or make a new pull request?

**Comment by kitadai31** [comment]
Please make a new PR.

**Pull request merged**
